-- Create new Account

CREATE USER RAHUL IDENTIFIED BY RAHUL;
GRANT DBA TO RAHUL;
GRANT ALL PRIVILEGES TO RAHUL;


-- Unlock HR account and grant access to new user
ALTER USER HR ACCOUNT UNLOCK;
ALTER USER HR IDENTIFIED BY HR;

GRANT SELECT ON HR.COUNTRIES TO RAHUL;
GRANT SELECT ON HR.DEPARTMENTS TO RAHUL;
GRANT SELECT ON HR.EMPLOYEES TO RAHUL;
GRANT SELECT ON HR.JOB_HISTORY TO RAHUL;
GRANT SELECT ON HR.JOBS TO RAHUL;
GRANT SELECT ON HR.LOCATIONS TO RAHUL;
GRANT SELECT ON HR.REGIONS TO RAHUL;

